-- ════════════════════════════════════════════════════════════
-- NÃO RODAR. Esta migração nunca foi aplicada e foi aposentada em 14/09/2026.
--
-- Ela criava users.numero_seq e documents.codigo para um código de 12 dígitos
-- (YYYY + número do integrador + número da proposta). As colunas nunca existiram
-- no banco, o código engolia o erro e o "número do integrador" saía 0001 para
-- todo mundo: 202600010001 ficou impresso em 94 propostas de 90 empresas.
--
-- Hoje o número impresso na proposta é o codigo_curto (YYYYNNNN), o mesmo do
-- link público /p/<slug>.<codigo_curto>. Ele é único por integrador pelo índice
-- idx_documents_user_codigo_curto_unique, que já existe no banco.
--
-- NÃO criar documents.codigo com UNIQUE: os códigos de 12 dígitos já impressos
-- se repetem entre clientes e dentro do mesmo cliente, e não se renumera
-- proposta já enviada.
-- ════════════════════════════════════════════════════════════
